---

- name: SSH | SSH configured for interactive user.
  block:
    - name: SSH | User SSH directory exists.
      ansible.builtin.file:
        path: "{{ item.home_dir }}/.ssh"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: "0700"
        state: directory
      loop: "{{ interactive_user }}"

    - name: SSH | User key login authorized.
      ansible.posix.authorized_key:
        user: "{{ item.username }}"
        key: "{{ item.pubkey }}"
      loop: "{{ interactive_user }}"
  when:
    - user is defined
    - user.use_ssh_key

- name: SSH | SSH configured for service account.
  block:
    - name: SSH | Service account SSH directory exists.
      ansible.builtin.file:
        path: "{{ item.home_dir }}/.ssh"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: "0700"
        state: directory
      loop: "{{ service_account }}"

    - name: SSH | Service account key login authorized.
      ansible.posix.authorized_key:
        user: "{{ item.username }}"
        key: "{{ item.pubkey }}"
      loop: "{{ service_account }}"

- name: SSH | SSHD enabled.
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true

- name: SSH | Root disallowed from SSH login.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^\s*PermitRootLogin yes
    line: "#PermitRootLogin yes"
  notify: restart-sshd
