---

- name: SSH | SSH configured for interactive user.
  block:
    - name: SSH | User SSH directory exists.
      ansible.builtin.file:
        path: "{{ user.home_dir }}/.ssh"
        owner: "{{ user.username }}"
        group: "{{ user.username }}"
        mode: "0700"
        state: directory
    - name: SSH | User key login authorized.
      ansible.posix.authorized_key:
        user: "{{ user.username }}"
        key: "{{ lookup('file', './keys/user/id_rsa.pub') }}"
  when:
    - user is defined
    - user.use_ssh_key

- name: SSH | SSH configured for service account.
  block:
    - name: SSH | Service account SSH directory exists.
      ansible.builtin.file:
        path: "{{ service_account.home_dir }}/.ssh"
        owner: "{{ service_account.username }}"
        group: "{{ service_account.username }}"
        mode: "0700"
        state: directory
    - name: SSH | Service account key login authorized.
      ansible.posix.authorized_key:
        user: "{{ service_account.username }}"
        key: "{{ lookup('file', './keys/service_account/id_rsa.pub') }}"

- name: SSH | SSHD enabled.
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true

- name: SSH | Root disallowed from SSH login.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^\s*PermitRootLogin yes
    line: "#PermitRootLogin yes"
  notify: restart-sshd
