---

- name: USERS | Determine the sudo users group name.
  shell: grep -oE "wheel|sudo" "/etc/group" | head -1
  changed_when: false
  register: sudo_group_name

- name: USERS | Interactive user exists.
  block:
    - name: USERS | Interactive user group exists.
      ansible.builtin.group:
        name: "{{ user.username }}"
    - name: USERS | Interactive user exists.
      ansible.builtin.user:
        name: "{{ user.username }}"
        comment: "{{ user.comment }}"
        group: "{{ user.username }}"
        groups: "{{ sudo_group_name.stdout }}"
        home: "{{ user.home_dir }}"
  when: user is defined

- name: USERS | Ansible service account exists.
  block:
    - name: USERS | Ansible group exists.
      ansible.builtin.group:
        name: "{{ service_account.username }}"
    - name: USERS | Ansible user exists.
      ansible.builtin.user:
        name: "{{ service_account.username }}"
        comment: "{{ service_account.comment }}"
        group: "{{ service_account.username }}"
        groups: "{{ sudo_group_name.stdout }}"
        home: "{{ service_account.home_dir }}"

- name: USERS | Sudoers configured.
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    insertbefore: "{{ item.insertbefore | default(omit) }}"
    owner: root
    group: root
    mode: "0440"
    validate: visudo -c -f %s
  loop:
    - line: "%{{ sudo_group_name.stdout }} ALL=(ALL) ALL"
      regexp: ^\s*%{{ sudo_group_name.stdout }}\s*ALL=(ALL)\s*ALL\s*
      insertbefore: BOF
    - line: Defaults env_keep += "http_proxy HTTP_PROXY https_proxy HTTPS_PROXY no_proxy NO_PROXY npm_config_proxy"
      regexp: ^\s*Defaults\s*env_keep\s*\+=\s*\"http_proxy\s*HTTP_PROXY\s*https_proxy\s*HTTPS_PROXY\s*no_proxy\s*NO_PROXY\s*npm_config_proxy\"\s*
    - line: Defaults env_keep += "EDITOR VISUAL SUDO_EDITOR TERM PAGER BROWSER SHELL"
      regexp: ^\s*Defaults\s*env_keep\s*\+=\s*\"EDITOR\s*VISUAL\s*SUDO_EDITOR\s*TERM\s*PAGER\s*BROWSER\s*SHELL\"\s*
    - line: "ansible ALL= NOPASSWD: ALL"
      regexp: ^\s*ansible\s*ALL=\s*NOPASSWD:\s*ALL\s*
