---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: freebsd-host
    box: generic/freebsd12
    memory: 1024
    cpus: 1
  - name: centos-host
    box: centos/7
    memory: 1024
    cpus: 1
  - name: arch-host
    box: archlinux/archlinux
    memory: 1024
    cpus: 1
  - name: ubuntu-host
    box: ubuntu/groovy64
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
  inventory:
    group_vars:
      all:
        interactive_account:
          username: alice
          comment: Alice
          home_dir: /home/alice
          pubkeys:
            - "{{ lookup('file', '../../keys/id_rsa.pub') }}"
        service_account:
          username: ansible
          comment: Service account
          home_dir: /var/lib/ansible
          pubkeys:
            - "{{ lookup('file', '../../keys/id_rsa.pub') }}"
verifier:
  name: ansible
